[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "ai-interview-platform-backend"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "fastapi",
    "httpx2",
    "PyMuPDF",
    "pydantic",
    "python-docx",
    "scikit-learn",
    "sqlalchemy",
    "uvicorn",
    "pytest",
]

[tool.pytest.ini_options]
pythonpath = ["."]
